### ISSUE TITLE
Set up translations

### ISSUE THREAD

**Issue by pixeldesu** [pixeldesu/videoline#10]
The interface in itself doesn't have many string labels yet, but before that increases, it'd be wise to set up a translation system.

**To Do:**
* Set up `vue-i18n` and move current hardcoded string labels into it

**Comment by ca1zr** [comment]
Could you assign this one to me?

**Comment by pixeldesu** [comment]
Resolved with cc592e69c67fa405e11276e2533402e4901f9312
